# Generated by Django 4.1.7 on 2023-02-15 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Имя')),
                ('job', models.CharField(blank=True, max_length=15, null=True, verbose_name='Должность')),
                ('lesson', models.CharField(blank=True, max_length=15, null=True, verbose_name='Предмет(если есть)')),
            ],
            options={
                'verbose_name': 'Создать Главного',
                'verbose_name_plural': 'Главные',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'Создать класса',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Klass_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=3, null=True, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Создать Число класса',
                'verbose_name_plural': 'Числа',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Имя')),
                ('lesson', models.CharField(blank=True, max_length=15, null=True, verbose_name='Предмет')),
                ('klass', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.klass', verbose_name='Класса')),
            ],
            options={
                'verbose_name': 'Создать Учителя',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.AddField(
            model_name='klass',
            name='klass_name',
            field=models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.klass_name', verbose_name='Цыфра класса'),
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Имя')),
                ('klass', models.ForeignKey(blank=True, max_length=20, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.klass', verbose_name='Класса')),
            ],
            options={
                'verbose_name': 'Создать Ученика',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
