# Generated by Django 4.1.7 on 2023-02-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_n'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, verbose_name='Название')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото 3')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата выпуска')),
                ('inf', models.TextField(blank=True, max_length=300, null=True, verbose_name='Иформация')),
            ],
        ),
        migrations.DeleteModel(
            name='n',
        ),
    ]
